% Auto-generated by cameraCalibrator app on 07-Jun-2016
%-------------------------------------------------------


% Define images to process
imageFileNames = {'/home/kaksoispiste/Code/calibpy/src/img/left1.png',...
    '/home/kaksoispiste/Code/calibpy/src/img/left10.png',...
    '/home/kaksoispiste/Code/calibpy/src/img/left11.png',...
    '/home/kaksoispiste/Code/calibpy/src/img/left2.png',...
    '/home/kaksoispiste/Code/calibpy/src/img/left3.png',...
    '/home/kaksoispiste/Code/calibpy/src/img/left4.png',...
    '/home/kaksoispiste/Code/calibpy/src/img/left5.png',...
    '/home/kaksoispiste/Code/calibpy/src/img/left6.png',...
    '/home/kaksoispiste/Code/calibpy/src/img/left7.png',...
    '/home/kaksoispiste/Code/calibpy/src/img/left8.png',...
    '/home/kaksoispiste/Code/calibpy/src/img/left9.png',...
    };

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Generate world coordinates of the corners of the squares
squareSize = 30;  % in units of 'mm'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParamsL, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'mm');

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParamsL, 'BarGraph');

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParamsL, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParamsL);

% For example, you can use the calibration data to remove effects of lens distortion.
originalImage = imread(imageFileNames{1});
undistortedImage = undistortImage(originalImage, cameraParamsL);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('SparseReconstructionExample')
